Bookshelf/Bookshelf/Models/Pages/BookPage.cs
using System;
using System.ComponentModel.DataAnnotations;
using EPiServer.Core;
using EPiServer.DataAbstraction;
using EPiServer.DataAnnotations;
using EPiServer.SpecializedProperties;
using EPiServer.Web;
using EPiServer;

namespace Bookshelf.Models.Pages
{
    [ContentType(GroupName = "Bookshelf Pages", DisplayName = "Book Page", GUID = "2773bed9-04b2-4373-bfa1-2a59fba34b40", Description = "This is a page for a book")]
    [ImageUrl("~/Resources/img/book-page.png")]
    
    public class BookPage : SitePageData
    {

        [Display(
        Name = "Subtitle",
        Description = "",
        GroupName = SystemTabNames.Content,
        Order = 10)]
        public virtual string SubTitle { get; set; }

        [Display(
         Name = "Author",
         Description = "",
         GroupName = SystemTabNames.Content,
         Order = 30)]
        public virtual string Author { get; set; }

        [Display(
         Name = "Publisher",
         Description = "",
         GroupName = SystemTabNames.Content,
         Order = 40)]
        public virtual string Publisher { get; set; }

       
        [Display(
          Name = "Links to find the book",
          Description = "",
          GroupName = SystemTabNames.Content,
          Order = 50)]
        public virtual LinkItemCollection BookLinks { get; set; }


        [Display(
           Name = "Short Description",
           Description = "",
           GroupName = SystemTabNames.Content,
           Order = 70)]
        public virtual XhtmlString ShortDescription { get; set; }

        [Display(
            Name = "Description",
            Description = "",
            GroupName = SystemTabNames.Content,
            Order = 80)]
        public virtual XhtmlString Description { get; set; }
    }
}

Bookshelf/Bookshelf/Models/ViewModels/PreviewModel.cs
using Bookshelf.Models.Pages;
using EPiServer.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bookshelf.Models.ViewModels
{
    public class PreviewModel : PageViewModel<SitePageData>
    {
        public PreviewModel(SitePageData currentPage, IContent previewContent)
            : base(currentPage)
        {
            PreviewContent = previewContent;
            Areas = new List<PreviewArea>();
        }

        public IContent PreviewContent { get; set; }
        public List<PreviewArea> Areas { get; set; }

        public class PreviewArea
        {
            public bool Supported { get; set; }
            public string AreaName { get; set; }
            public string AreaTag { get; set; }
            public ContentArea ContentArea { get; set; }
        }
    }
}

Bookshelf/Bookshelf/Controllers/BookPageController.cs
using System.Web.Mvc;
using Bookshelf.Models.Pages;
using Bookshelf.Models.ViewModels;
using EPiServer.Web.Mvc;
using EPiServer.Core;
using System.Collections.Generic;
using EPiServer.DataAbstraction;
using Bookshelf.Business;
using EPiServer.ServiceLocation;

namespace Bookshelf.Controllers
{
    public class BookPageController : PageControllerBase<BookPage>
    {
        public ActionResult Index(BookPage currentPage)
        {
            PageViewModel<BookPage> model = new PageViewModel<BookPage>(currentPage);
            var editHints = ViewData.GetEditHints<PageViewModel<BookPage>, BookPage>();
            editHints.AddConnection(m => m.CurrentPage.Category, p => p.Category);
            return View(model);
        }

        public ActionResult Preview(PageData currentPage, PageListModel bookModel)
        {
            var pd = (BookPage)currentPage;


            var model = new BookItemModel(pd)
            {
                Tags = GetTags(pd),
            };

            return PartialView("Preview", model);
        }

        public ActionResult Full(BookPage currentPage)
        {

            var model = new BookItemModel(currentPage)
            {
                Category = currentPage.Category,
                Tags = GetTags(currentPage)
               
            };

            var editHints = ViewData.GetEditHints<BookItemModel, BookPage>();
            editHints.AddConnection(m => m.Category, p => p.Category);
            editHints.AddFullRefreshFor(p => p.Category);
            editHints.AddFullRefreshFor(p => p.StartPublish);

            return PartialView("Full", model);
        }

        public IEnumerable<BookItemModel.TagItem> GetTags(BookPage currentPage)
        {
            List<BookItemModel.TagItem> tags = new List<BookItemModel.TagItem>();
            var categoryRepository = ServiceLocator.Current.GetInstance<CategoryRepository>();

            foreach (var item in currentPage.Category)
            {
                Category cat = categoryRepository.Get(item);

                tags.Add(new BookItemModel.TagItem() { Title = cat.Name, Url = TagFactory.Instance.GetTagUrl(currentPage, cat) });
            }

            return tags;
        }

    }
}

Bookshelf/Bookshelf/Views/BookPage/Full.cshtml
@using EPiServer.Core
@using EPiServer.Editor
@using EPiServer.Web.Mvc.Html
@using Bookshelf.Models.ViewModels

@model BookItemModel

<form class="form-horizontal">
    <div class="form-group">
        @if (!string.IsNullOrEmpty(Model.CurrentPage.Category.ToString()))
        {
            <label class="col-xs-2">@Html.LabelFor(x => x.CurrentPage.Category):</label>
            <div class="col-xs-10">
                <div @Html.EditAttributes("PageCategory")>
                    @foreach (var item in Model.Tags)
                    {
                        <a href="@item.Url">@item.Title</a>
                    }
                </div>
            </div>
        }
    </div>
</form>

Bookshelf/Bookshelf/Views/BookPage/Index.cshtml
@model Bookshelf.Models.ViewModels.PageViewModel<Bookshelf.Models.Pages.BookPage>

@{ Layout = "~/Views/Shared/Layouts/_SubHeaderNoRelatedContent.cshtml"; }

<div class="row">
    <div class="col-md-12">
        <h1 class="titleMargin">@Html.PropertyFor(x => x.CurrentPage.PageName)</h1>
        <h4 class="titleMargin">@Html.PropertyFor(x => x.CurrentPage.SubTitle)</h4>
       
        <br />
        <div class="col-md-4">
            <div class="cover-image">
                @Html.PropertyFor(x => x.CurrentPage.PageImage)
            </div>
        </div>
        <div class="col-md-8">      
            @Html.Action("Full", "BookPage", new { currentPage = Model.CurrentPage })

            <form class="form-horizontal">             
                <div class="form-group">
                    <label class="col-xs-2">@Html.LabelFor(x => x.CurrentPage.Author):</label>
                    <div class="col-xs-10">@Html.PropertyFor(x => x.CurrentPage.Author)</div>
                </div>
            </form>

            <form class="form-horizontal">
                <div class="form-group">
                    <label class="col-xs-2">@Html.LabelFor(x => x.CurrentPage.Publisher):</label>
                    <div class="col-xs-10">@Html.PropertyFor(x => x.CurrentPage.Publisher)</div>
                </div>
            </form>

            <p>@Html.PropertyFor(x => x.CurrentPage.BookLinks)</p>
           
            <br />
            @Html.PropertyFor(x => x.CurrentPage.ShortDescription)
            @Html.PropertyFor(x => x.CurrentPage.Description)
        </div>
    </div>
</div>
<br />

Bookshelf/Bookshelf/Views/BookPage/Preview.cshtml
@using EPiServer.Core
@using EPiServer.Editor
@using EPiServer.Web.Mvc.Html
@using Bookshelf.Models.ViewModels

@model BookItemModel

<div class="listResult">
    <h3>
        @Html.PageLink(Model.CurrentPage)
    </h3>
  
    <span>Category:
        @foreach (var item in Model.Tags)
        {
            <span class="icon-tags">&nbsp;  </span>   <a href="@item.Url">@item.Title</a>
            @Html.PropertyFor(x => x.CurrentPage.Author)
        }
    </span>
    <hr />
</div>